FROM alpine:3.8 as downloader

RUN apk update &&\
    apk --no-cache add git

#Fetch repo
RUN git clone https://github.com/eduardo010174/GSHADE.git &&\
    cd GSHADE/ &&\
    cd util/ &&\
    git clone https://github.com/eduardo010174/MIRACL.git

FROM alpine:3.8 as compiler

RUN apk update &&\
    apk --no-cache add \
        g++ \
        make \
        gmp-dev \
        openssl-dev

COPY --from=0 /GSHADE /GSHADE
WORKDIR /GSHADE

#Compile Miracl
RUN cd util/ &&\
    mkdir -p ./Miracl/ &&\
    find ./MIRACL/ -type f -exec cp ${PWD}/'{}' ${PWD}/Miracl/ \; &&\
    cd ./Miracl/ &&\
    sh linux64 &&\
    find . -type f -not -name '*.a' -not -name '*.h' -not -name '*.o' -not -name '.git*' | xargs rm

#Compile GSHADE
RUN make

FROM alpine:3.8 as runner

RUN apk update &&\
    apk --no-cache add \
        gmp \
        openssl

COPY --from=1 /GSHADE/dst.exe /GSHADE/dst.exe
WORKDIR /GSHADE
