FROM alpine:3.8 as downloader

RUN apk update &&\
    apk --no-cache add \
        git \
        g++ \
        make \
        gmp-dev \
        openssl-dev

RUN git clone https://github.com/eduardo010174/GSHADE.git &&\
    cd GSHADE/ &&\
    cd util/ &&\
    git clone https://github.com/miracl/MIRACL.git

WORKDIR /GSHADE

RUN cd util/ &&\
    mkdir -p ./Miracl/ &&\
    find ./MIRACL/ -type f -exec cp ${PWD}/'{}' ${PWD}/Miracl/ \; &&\
    cd ./Miracl/ &&\
    sh linux64 &&\
    find . -type f -not -name '*.a' -not -name '*.h' -not -name '*.o' -not -name '.git*'| xargs rm

RUN make
